apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: lolo-frontend-main-pipeline 
  description: Main promotion pipeline for Lolo App - Deploy v2
serialPipeline:
  stages:
  - targetId: dev
    profiles: [dev]
  - targetId: staging
    profiles: [staging]
  - targetId: prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment v2
run:
  location: projects/lolo-app-dev-1/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: "ci-cloud-deploy@lolo-app-dev-1.iam.gserviceaccount.com"
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging environment
run:
  location: projects/lolo-app-staging-1/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  - VERIFY
  serviceAccount: "ci-cloud-deploy@lolo-app-dev-1.iam.gserviceaccount.com"
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production environment
requireApproval: true
run:
  location: projects/lolo-app-prod-1/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: "ci-cloud-deploy@lolo-app-dev-1.iam.gserviceaccount.com"
