apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: uselolo-lolo-app-dev-1
spec:
  template:
    spec:
      containers:
        - image: lolo-frontend-image
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
