apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: lolo-frontend-dev-pipeline
description: dev fast feedback pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: [dev]
    strategy:
      standard:
        verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run development service
run:
  location: projects/lolo-app-dev-1/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Dev environment v2
run:
  location: projects/lolo-app-dev-1/locations/us-central1
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: "ci-cloud-deploy@lolo-app-dev-1.iam.gserviceaccount.com"