# cloudbuild-dev.yaml (With Integration Tests)

options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1. Unit Tests
# Run a clean install and then execute tests in a single step.
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'sh'
  args: ['-c', 'npm ci && npm run test']

# 2. Build images with Skaffold
# Skaffold builds both images defined in skaffold.yaml and saves the
# exact image names (with digests) to a file for the next step.
- name: 'gcr.io/k8s-skaffold/skaffold:v2.12.0'
  entrypoint: 'skaffold'
  dir: 'cicd'
  args:
    - build
    - '-p=dev'
    - '--tag=${SHORT_SHA}'
    - '--file-output=artifacts.json'
    - '-f=skaffold.yaml'

# 4. Push Images to Registry
# We must explicitly push the images before creating the Cloud Deploy release.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/lolo-app/lolo-frontend-image:${SHORT_SHA}']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/lolo-app/test-runner:${SHORT_SHA}']

# 5. Create a Cloud Deploy Release
# This step hands off the built images to your delivery pipeline.
# Cloud Deploy will then manage the deployment to dev and run the
# verification tests defined in the 'dev' profile of skaffold.yaml.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'deploy'
    - 'releases'
    - 'create'
    # The release name includes the short commit SHA for traceability
    - 'release-${SHORT_SHA}'
    - '--delivery-pipeline=lolo-frontend-dev-pipeline'
    - '--region=us-central1'
    - '--source=cicd'
    # Use the artifact file generated by the skaffold build step
    - '--build-artifacts=cicd/artifacts.json'
    - '--gcs-source-staging-dir=gs://lolo-cd-artifacts-lolo-app-dev-1/test-folder'
