steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    id: 'install'

  # Step 2: Build Next.js with BUILD_ID
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    id: 'build'
    env:
      - 'BUILD_ID=${SHORT_SHA}'
      - 'NEXT_PUBLIC_CDN_URL=https://storage.googleapis.com/${_STATIC_BUCKET}/${SHORT_SHA}'
    waitFor: ['install']

  # Step 3: Upload static assets to GCS under same BUILD_ID
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-static-assets'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploading static assets for build ${SHORT_SHA}..."
        gsutil -m -h "Cache-Control:public, max-age=31536000, immutable" \
          cp -r .next/static/* \
          gs://${_STATIC_BUCKET}/${SHORT_SHA}/_next/static/
        gsutil -m -h "Cache-Control:public, max-age=86400" \
          cp -r public/* \
          gs://${_STATIC_BUCKET}/${SHORT_SHA}/public/
        echo "Static assets uploaded successfully."
    waitFor: ['build']

  # Step 4: Verify assets
  - name: 'gcr.io/cloud-builders/curl'
    id: 'verify-assets'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verifying CDN accessibility..."
        curl -sf "https://storage.googleapis.com/${_STATIC_BUCKET}/${SHORT_SHA}/_next/static/" || true
        echo "CDN verification complete."
    waitFor: ['upload-static-assets']

  # Step 5: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build', '-f', 'Dockerfile.prod',
        '--build-arg', 'BUILD_ID=${SHORT_SHA}',
        '--build-arg', 'NEXT_PUBLIC_CDN_URL=https://storage.googleapis.com/${_STATIC_BUCKET}/${SHORT_SHA}',
        '-t', 'us-central1-docker.pkg.dev/rich-torus-428117-m8/lolo-frontend-dev/lolo-frontend:$SHORT_SHA',
        '-t', 'us-central1-docker.pkg.dev/rich-torus-428117-m8/lolo-frontend-dev/lolo-frontend:${BRANCH_NAME}-latest',
        '.'
      ]
    id: 'build-image'
    waitFor: ['verify-assets']

  # Step 6: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/rich-torus-428117-m8/lolo-frontend-dev/lolo-frontend']
    id: 'push-image'
    waitFor: ['build-image']

  # Step 7: Deploy to Cloud Run with runtime env vars
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'lolo-legacy-frontend-dev',
        '--image', 'us-central1-docker.pkg.dev/rich-torus-428117-m8/lolo-frontend-dev/lolo-frontend:$SHORT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--set-env-vars', 'BUILD_ID=${SHORT_SHA},_STATIC_BUCKET=${_STATIC_BUCKET}'
      ]
    id: 'deploy'
    waitFor: ['push-image']

substitutions:
  _REGION: us-central1
  _STATIC_BUCKET: 'lolo-frontend-static-assets'


# Cloud Build options
options:
  logging: CLOUD_LOGGING_ONLY